### ISSUE TITLE
Hi, you still make translation for 6.2?

### ISSUE THREAD

**Issue by Dev-Archsoft** [lmfaoown/Aion-6.0-Translation#1]
Hi, you still make translation for 6.x? I've xml combiner for aion strings, if you want PM me to my skype :)
dev.archsoft@gmail.com

**Comment by AyserJamshidi** [comment]
Hello.  No I don't play Korea anymore and no longer update the
translations.  I made my own program to translate and input everything on
its own, thank you very much though.

**Comment by Dev-Archsoft** [comment]
Ok, thanks for reply :)
